controller_joint_names: ['', 'Joint_DW1', 'Joint_DW2', 'Joint_LIW1', 'Joint_IW1', 'Joint_IW2', 'Joint_DA1', 'Joint_IA1', 'Joint_EP1', 'Joint_IA2', 'Joint_DA2', 'Joint_IA3', 'Joint_IA4', 'Joint_DA3', 'Joint_IA5', 'Joint_IA6', ]
